<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Distribuições Amostrais – Bioestatística Usando o R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./12-estimacao.html" rel="next">
<link href="./10-assimetria.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-probabilidades.html">Parte IV - Probabilidades e Distribuições</a></li><li class="breadcrumb-item"><a href="./11-distAmostrais.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bioestatística Usando o R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte I - Fundamentos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Natureza dos Dados</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-producaoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Produção dos Dados</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte II - Ambiente Computacional com R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-introducaoR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introdução ao uso do R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-manipulandoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulando dados no R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte III - Estatística Descritiva</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-medidasResumidoras.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Medidas Resumidoras</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-tabelas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tabelas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-graficos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Gráficos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte IV - Probabilidades e Distribuições</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-probabilidades.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introdução à Teoria das Probabilidades</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assimetria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Assimetria e Curtose</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-distAmostrais.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte V - Inferência Estatística</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-estimacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Estimação</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-testeHipoteses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Teste de Hipóteses</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte VI - Testes Paramétricos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-teste-t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Comparação entre duas médias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Análise de Variância</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-anovaRep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Anova de Medidas Repetidas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte VII - Relações entre Variáveis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-correlacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Correlação</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-regressao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Regressão Linear Simples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte VIII - Métodos Não Paramétricos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-dadoscategoricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Análise de Dados Categóricos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-testes-naoParametricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Métodos não paramétricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte IX - Bioestatística Aplicada à Epidemiologia</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-testesDiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Determinação da validade e confiabilidade de testes diagnósticos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-medidasOcorrencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Medidas de ocorrência de doença</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-sobrevida.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Análise de Sobrevida</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-reglogbin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Regressão Logística Binária</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glossario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossário</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#pacotes-necessários-para-este-capítulo" id="toc-pacotes-necessários-para-este-capítulo" class="nav-link active" data-scroll-target="#pacotes-necessários-para-este-capítulo"><span class="header-section-number">11.1</span> Pacotes necessários para este capítulo</a></li>
  <li><a href="#distribuições-populacional-e-amostral" id="toc-distribuições-populacional-e-amostral" class="nav-link" data-scroll-target="#distribuições-populacional-e-amostral"><span class="header-section-number">11.2</span> Distribuições populacional e amostral</a>
  <ul class="collapse">
  <li><a href="#distribuição-populacional" id="toc-distribuição-populacional" class="nav-link" data-scroll-target="#distribuição-populacional"><span class="header-section-number">11.2.1</span> Distribuição populacional</a></li>
  <li><a href="#sec-dam" id="toc-sec-dam" class="nav-link" data-scroll-target="#sec-dam"><span class="header-section-number">11.2.2</span> Distribuição amostral</a></li>
  </ul></li>
  <li><a href="#erros-amostrais-e-não-amostrais" id="toc-erros-amostrais-e-não-amostrais" class="nav-link" data-scroll-target="#erros-amostrais-e-não-amostrais"><span class="header-section-number">11.3</span> Erros amostrais e não amostrais</a></li>
  <li><a href="#média-e-desvio-padrão-da-média" id="toc-média-e-desvio-padrão-da-média" class="nav-link" data-scroll-target="#média-e-desvio-padrão-da-média"><span class="header-section-number">11.4</span> Média e desvio padrão da média</a></li>
  <li><a href="#sec-tcl" id="toc-sec-tcl" class="nav-link" data-scroll-target="#sec-tcl"><span class="header-section-number">11.5</span> Teorema do Limite Central (TCL)</a>
  <ul class="collapse">
  <li><a href="#exemplo-com-uma-variável-assimétrica" id="toc-exemplo-com-uma-variável-assimétrica" class="nav-link" data-scroll-target="#exemplo-com-uma-variável-assimétrica"><span class="header-section-number">11.5.1</span> Exemplo com uma variável assimétrica</a></li>
  </ul></li>
  <li><a href="#sec-popamostra" id="toc-sec-popamostra" class="nav-link" data-scroll-target="#sec-popamostra"><span class="header-section-number">11.6</span> Proporções populacional e amostral</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-probabilidades.html">Parte IV - Probabilidades e Distribuições</a></li><li class="breadcrumb-item"><a href="./11-distAmostrais.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-cap11" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="pacotes-necessários-para-este-capítulo" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="pacotes-necessários-para-este-capítulo"><span class="header-section-number">11.1</span> Pacotes necessários para este capítulo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               e1071, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               ggplot2, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               knitr, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               readxl)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="distribuições-populacional-e-amostral" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="distribuições-populacional-e-amostral"><span class="header-section-number">11.2</span> Distribuições populacional e amostral</h2>
<p>Métricas como a média, a mediana e o desvio padrão são medidas numéricas de resumo. Quando calculadas a partir de dados de uma amostra são denominadas <strong>estatísticas amostrais</strong>. Por outro lado, as mesmas medidas numéricas de resumo calculadas para dados populacionais são chamadas de <strong>parâmetros populacionais</strong>.</p>
<p>Um parâmetro populacional é sempre uma constante, enquanto uma estatística de amostra é sempre uma variável aleatória. Como cada variável aleatória deve possuir uma distribuição de probabilidade, cada estatística de amostra possui uma distribuição de probabilidade. A distribuição de probabilidade de uma estatística de amostra é mais comumente chamada de <strong>distribuição amostral</strong>. Os conceitos abordados neste capítulo são a base da <strong>estatística inferencial</strong>.</p>
<section id="distribuição-populacional" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="distribuição-populacional"><span class="header-section-number">11.2.1</span> Distribuição populacional</h3>
<p>A distribuição populacional é a distribuição de probabilidade derivada das informações sobre todos os elementos de uma <strong>população</strong>.</p>
<p>Para fins de raciocínio didático, o conjunto de dados de 1368 observações de puérperas e recém-nascidos da Maternidade-escola do Hospital Geral de Caxias do Sul, RS, será considerado uma população. O gráfico da <a href="10-assimetria.html#fig-histbxp" class="quarto-xref">Figura&nbsp;<span>10.1</span></a>, da <a href="10-assimetria.html#sec-assimetria" class="quarto-xref"><span>Seção 10.2.1</span></a>, mostra a distribuição da <code>altura</code> das puérperas dessa ‘população’. Os parâmetros (<span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>) dessa “<em>população</em>” são:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(altura)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a> media <span class="ot">=</span> <span class="fu">mean</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">round</span>(media, <span class="dv">3</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.598</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a> dp <span class="ot">=</span> <span class="fu">sd</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">round</span>(dp, <span class="dv">3</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.065</code></pre>
</div>
</div>
</section>
<section id="sec-dam" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="sec-dam"><span class="header-section-number">11.2.2</span> Distribuição amostral</h3>
<p>Conforme mencionado no início deste capítulo, o valor de um parâmetro da população é sempre constante. Por exemplo, para qualquer conjunto de dados populacionais, há apenas um valor para a média populacional, <span class="math inline">\(\mu\)</span>.</p>
<p>No entanto, não se pode dizer o mesmo sobre a média amostral. Amostras diferentes do mesmo tamanho, retiradas da mesma população, produzem valores diferentes da média amostral, <span class="math inline">\(\bar{x}\)</span>. O valor da média amostral, para qualquer amostra, dependerá dos elementos incluídos nessa amostra. Em decorrência, a média amostral é uma variável aleatória. Portanto, como outras variáveis aleatórias, a média amostral possui uma distribuição de probabilidade, que é mais comumente chamada de <strong>distribuição amostral da média</strong>.</p>
<p>Outras estatísticas de amostra, como mediana, moda e desvio padrão, também possuem distribuições amostrais. Em geral, a distribuição de probabilidades de uma amostra é denominada de <strong>distribuição amostral</strong>.</p>
<p>Usar a variável <code>altura</code> das puérperas da Maternidade do HGCS como a população de interesse é apenas uma estratégia didática. Raramente, na vida real, é possível obter dados da população inteira. Reunir essa informação costuma ser muito custoso ou impossível. Por essa razão, a prática é selecionar apenas uma amostra da população e a usar para compreender as suas características.</p>
<p>A função <code>slice_sample()</code> do pacote <code>dplyr</code>extrairá uma amostra <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> de n = 30 da população. As funções <code>mean()</code> e <code>sd()</code> calcularão a média e o desvio padrão, repectivamente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">234</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>amostra1 <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>media1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra1<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>dp1 <span class="ot">&lt;-</span>  <span class="fu">sd</span>(amostra1<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(media1, dp1))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.59266667 0.06073875</code></pre>
</div>
</div>
<p>Se este processo for repetido várias vezes, a cada amostra aleatória <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, serão gerados médias e desvios padrão diferentes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">236</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>amostra2 <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>media2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra2<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>dp2 <span class="ot">&lt;-</span>  <span class="fu">sd</span>(amostra2<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(media2, dp2))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.60633333 0.06960397</code></pre>
</div>
</div>
<p>À medida que o número de amostras possíveis forem aumentando, elas constituem uma distribuição cuja média, média das médias, <span class="math inline">\(\bar{x}_{\bar{x}}\)</span>, é igual a média populacional, <span class="math inline">\(\mu\)</span>. Essa distribuição, no caso da média, recebe o nome de <strong>distribuição amostral das médias</strong>.</p>
<p>Agora, para exemplificar este conceito, serão geradas 5000 amostras e calculada a média de cada uma das amostras de n = 30 que constituirão a distribuição, mostrada no gráfico da <a href="#fig-dam" class="quarto-xref">Figura&nbsp;<span>11.1</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extraindo 5000 amostras</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>amostras5000 <span class="ot">&lt;-</span> <span class="fu">rep</span> (<span class="dv">0</span>, <span class="dv">5000</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5000</span>) {</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  amostra <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">slice_sample</span> (<span class="at">n =</span> <span class="dv">30</span>) </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  amostras5000 [i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra<span class="sc">$</span>altura)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Media e desvio padrão das 5000 amostras:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">mean</span> (amostras5000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">sd</span> (amostras5000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(mu, sigma))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.598 0.012</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-dam" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-distAmostrais_files/figure-html/fig-dam-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.1: Distribuição amostral das médias de 5000 amostras de n = 30
</figcaption>
</figure>
</div>
</div>
</div>
<p>Se a média, <span class="math inline">\(\bar{x}_{\bar{x}}\)</span>, dessas 5000 amostras de n = 30, for comparada com a média populacional, <span class="math inline">\(\mu\)</span>, observa-se que até 3 dígitos decimais não há uma diferença. Entretanto, o desvio padrão é bem menor (0.012) que o da população (0.065).</p>
</section>
</section>
<section id="erros-amostrais-e-não-amostrais" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="erros-amostrais-e-não-amostrais"><span class="header-section-number">11.3</span> Erros amostrais e não amostrais</h2>
<p>Amostras diferentes selecionadas da mesma população darão resultados diferentes porque contêm elementos diferentes. Isso é evidente nas medias das amostra1 e amostra2, 1.593m e 1.606m, respectivamente, comparadas com a média da população igual a 1.598m .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>erro1 <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">mean</span>(amostra1<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">mean</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>erro2 <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">mean</span>(amostra2<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">mean</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(erro1, erro2), <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0053 0.0084</code></pre>
</div>
</div>
<p>Se outras amostras forem extraídas, o resultado obtido de qualquer amostra geralmente será diferente do resultado obtido da população correspondente. A diferença entre o valor de uma estatística amostral obtida de uma amostra e o valor do parâmetro populacional correspondente, é chamado de <strong>erro amostral</strong>. Observe que essa diferença representa o erro amostral apenas se a amostra for aleatória e não houver nenhum erro não amostral. Caso contrário, apenas uma parte dessa diferença será devido ao erro amostral.</p>
<p><span class="math display">\[
erro \quad amostral = \bar{x}_{i} - \mu  
\]</span></p>
<p>É importante lembrar que o erro amostral ocorre devido ao acaso. Não é possível evitar o erro amostral. É possível limitar o seu valor através da seleção de uma amostra adequada. Os erros que ocorrem por outros motivos, como erros cometidos durante a coleta, registro e tabulação dos dados, são chamados de <strong>erros não amostrais</strong>. Esses erros ocorrem, em geral, por causa de erros humanos e não por acaso.</p>
</section>
<section id="média-e-desvio-padrão-da-média" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="média-e-desvio-padrão-da-média"><span class="header-section-number">11.4</span> Média e desvio padrão da média</h2>
<p>A média e o desvio padrão calculados para a distribuição amostral da média são chamados de <em>média (</em><span class="math inline">\(\mu_{\bar{x}}\)</span>) e <em>desvio padrão (</em><span class="math inline">\(\sigma_{\bar{x}}\)</span>) da média. Na verdade, a média e o desvio padrão da média são, respectivamente, a média e o desvio padrão das médias de todas as amostras do mesmo tamanho selecionadas de uma população. O desvio padrão da média é, comumente, chamado de <strong>erro padrão da média</strong> (<span class="math inline">\(\sigma_{\bar{x}}\)</span>).</p>
<p>A média amostral, <span class="math inline">\(\bar{x}\)</span>, é chamada de <em>estimador</em> da média da população, <span class="math inline">\(\mu\)</span>. Quando o valor esperado (ou média) de uma estatística amostral é igual ao valor do parâmetro populacional correspondente, essa estatística amostral é considerada um estimador não enviesado, consistente.<br>
Para a média amostral <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\mu_{\bar{x}} = \mu\)</span>. Logo, <span class="math inline">\(\bar{x}\)</span>, é um estimador imparcial de <span class="math inline">\(\mu\)</span>. Esta é uma propriedade muito importante que um estimador deve possuir. No entanto, o desvio padrão da média, <span class="math inline">\(\sigma_{\bar{x}}\)</span>, não é igual ao desvio padrão, <span class="math inline">\(\sigma\)</span>, da distribuição populacional (a menos que n = 1). O desvio padrão da média amostral é igual ao desvio padrão da população dividido pela raiz quadrada do tamanho amostral:</p>
<p><span class="math display">\[
\sigma_{\bar{x}} = \frac {\sigma}{\sqrt{n}}
\]</span></p>
<p>A dispersão da distribuição amostral da média é menor do que dispersão da distribuição populacional correspondente, como mostrado acima. Em outras palavras, <span class="math inline">\(\sigma_{\bar{x}} &lt; \sigma\)</span>. Isso é visível na fórmula do <span class="math inline">\(\sigma_{\bar{x}}\)</span> . Quando <em>n</em> é maior que 1, o que geralmente é verdadeiro, o denominador em <span class="math inline">\(\frac {\sigma}{\sqrt{n}}\)</span> é maior que 1. Desta forma, <span class="math inline">\(\sigma_{\bar{x}}\)</span> é menor que <span class="math inline">\(\sigma\)</span>. O desvio padrão da distribuição amostral da média diminui à medida que o tamanho amostral aumenta.</p>
<p>Sempre que o <em>n</em> for grande, em geral &gt; 30 <span class="citation" data-cites="pagano2000sampling">(<a href="referencias.html#ref-pagano2000sampling" role="doc-biblioref">1</a>)</span>, pode ser assumido que a distribuição será uma curva normal e que o desvio padrão da amostra (<em>s</em>) é um estimador não enviesado do desvio padrão populacional (<span class="math inline">\(\sigma\)</span>). Então, o erro padrão da média (<span class="math inline">\(\sigma_{\bar{x}}\)</span>) pode ser estimado pelo <span class="math inline">\(EP_{\bar{x}}\)</span>:</p>
<p><span class="math display">\[
EP_{\bar{x}} = \frac {s}{\sqrt{n}}
\]</span></p>
</section>
<section id="sec-tcl" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="sec-tcl"><span class="header-section-number">11.5</span> Teorema do Limite Central (TCL)</h2>
<p>Na maioria das vezes, a população da qual as amostras são extraídas não é normalmente distribuída. Em tais casos, a forma da distribuição amostral de X é inferida de um teorema muito importante chamado <em>teorema do limite central</em>. De acordo com este teorema para um grande tamanho de amostra (em geral, acima de 30), a distribuição amostral da média é aproximadamente normal, independentemente da forma da distribuição da população <span class="citation" data-cites="pagano2000sampling">(<a href="referencias.html#ref-pagano2000sampling" role="doc-biblioref">1</a>)</span>. Esta aproximação tornar-se-á mais acurada à medida que aumenta o tamanho amostral:</p>
<ul>
<li>a média da distribuição amostral, <span class="math inline">\(\mu_{\bar{x}}\)</span>, é igual a média populacional, <span class="math inline">\(\mu\)</span>;</li>
<li>desvio padrão da distribuição amostral, <span class="math inline">\(\sigma_{\bar{x}}\)</span>, é igual a <span class="math inline">\(\frac {\sigma}{\sqrt{n}}\)</span>;</li>
<li>o erro padrão da média, <span class="math inline">\(\sigma_{\bar{x}}\)</span>, é sempre menor (<a href="#fig-standard" class="quarto-xref">Figura&nbsp;<span>11.2</span></a>) que o desvio padrão populacional, <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-standard" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-standard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://i.imgur.com/I2CxksB.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-standard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.2: Erro padrão versus desvio padrão
</figcaption>
</figure>
</div>
</div>
</div>
<section id="exemplo-com-uma-variável-assimétrica" class="level3" data-number="11.5.1">
<h3 data-number="11.5.1" class="anchored" data-anchor-id="exemplo-com-uma-variável-assimétrica"><span class="header-section-number">11.5.1</span> Exemplo com uma variável assimétrica</h3>
<p>Como exemplo, será explorada a variável <code>renda</code>, do conjunto de dados <code>dadosMater.xlsx</code>, que representa a renda familiar em salários mínimos (<em>sm</em>). Como foi feito anteriormente, suponha que essa variável seja a “população” de estudo. Ela tem as seguintes medidas resumidoras e de assimetria:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (renda) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span> (<span class="at">media.sm =</span> <span class="fu">mean</span> (dados<span class="sc">$</span>renda, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dp.sm =</span> <span class="fu">sd</span>(dados<span class="sc">$</span>renda, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mediana.sm =</span> <span class="fu">median</span>(dados<span class="sc">$</span>renda, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">assimetria =</span> e1071<span class="sc">::</span><span class="fu">skewness</span>(dados<span class="sc">$</span>renda),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">curtose =</span> e1071<span class="sc">::</span><span class="fu">kurtosis</span>(dados<span class="sc">$</span>renda))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>resumo</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  media.sm dp.sm mediana.sm assimetria curtose
     &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1     2.22  1.23       1.92       2.22    8.21</code></pre>
</div>
</div>
<p>O desvio padrão é grande em relação à média, com um coeficiente de variação de 55.1% e uma mediana &lt; média. Estas métricas junto com os coeficientes de assimetria e curtose apontam para a assimetria positiva da variável <code>renda</code>. O gráfico da <a href="#fig-skewpos" class="quarto-xref">Figura&nbsp;<span>11.3</span></a> confirma esta afirmação:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-skewpos" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-skewpos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-distAmostrais_files/figure-html/fig-skewpos-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-skewpos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.3: Distribuição assimétrica positiva
</figcaption>
</figure>
</div>
</div>
</div>
<p>Os valores da média e do desvio padrão calculados para a distribuição de probabilidade dessa população fornecem os valores dos parâmetros populacionais <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>. Esses valores são <span class="math inline">\(\mu\)</span> =2.22 <em>sm</em> <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> e <span class="math inline">\(\sigma\)</span> =1.23 <em>sm</em>.<br>
Se extrairmos múltiplas amostras dessa população, observa-se a modificação do formato da distribuição à medida que aumenta o tamanho amostral, se aproximando progressivamente do modelo normal, com um número grande de amostras.</p>
<p><u>Extração de múltiplas amostras(1000)</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>amostras1000 <span class="ot">&lt;-</span> <span class="fu">rep</span> (<span class="dv">0</span>, <span class="dv">1000</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  amostra.sm <span class="ot">&lt;-</span> <span class="fu">sample</span> (dados<span class="sc">$</span>renda, <span class="dv">30</span>) </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  amostras1000 [i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra.sm)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><u>Media e desvio padrão das 1000 amostras</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">mean</span> (amostras1000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">sd</span> (amostras1000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>md <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">median</span>(amostras1000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(mu, sigma, md))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.231 0.236 2.224</code></pre>
</div>
</div>
<p><u>Assimetria e curtose</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> e1071<span class="sc">::</span><span class="fu">skewness</span>(amostras1000)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> e1071<span class="sc">::</span><span class="fu">kurtosis</span>(amostras1000)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(b1, b2))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4357889 0.2241975</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-semskew" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-semskew-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-distAmostrais_files/figure-html/fig-semskew-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:70.0%;height:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-semskew-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.4: Distribuição praticamente normal
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ou seja, extraindo-se 1000 amostras de n = 30 e calculando as mesmas métricas anteriores, observa-se que, embora a distribuição populacional original seja assimétrica, a distribuição amostral da média se aproxima bastante da distribuição gaussiana (<a href="#fig-semskew" class="quarto-xref">Figura&nbsp;<span>11.4</span></a>).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importância do Teorema do Limite Central
</div>
</div>
<div class="callout-body-container callout-body">
<p>O TCL é um dos pilares da inferência estatística. Entender a sua importância é como destrancar a porta para aplicar testes, construir intervalos de confiança e fazer previsões com segurança, mesmo quando os dados parecem confusos.</p>
<p>O TCL afirma que:</p>
<blockquote class="blockquote">
<p>A distribuição das médias amostrais tende a ser normal, mesmo que a população original não seja, desde que o tamanho da amostra seja suficientemente grande.</p>
</blockquote>
</div>
</div>
</section>
</section>
<section id="sec-popamostra" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="sec-popamostra"><span class="header-section-number">11.6</span> Proporções populacional e amostral</h2>
<p>O conceito de proporção é o mesmo que o conceito de frequência relativa e o conceito de probabilidade de sucesso em um experimento binomial, discutidos anteriormente, na distribuição binomial.</p>
<p>A frequência relativa de uma categoria ou classe dá a proporção da amostra ou população que pertence a essa categoria ou classe. Da mesma forma, a probabilidade de sucesso em um experimento binomial representa a proporção da amostra ou população que possui uma determinada característica.</p>
<p>A proporção populacional, representada por <em>p</em>, é obtida considerando a razão entre o número de elementos em uma população com uma característica específica e o número total de elementos na população. A proporção amostral, denotada por <span class="math inline">\(\hat{p}\)</span> (pronuncia-se p-chapéu), fornece uma proporção semelhante para uma amostra.</p>
<p><span class="math display">\[
p = \frac{X}{N} \quad e \quad \hat{p}= \frac{x}{n}
\]</span> onde,</p>
<ul>
<li><em>N</em> <span class="math inline">\(\to\)</span> número total de elementos em uma população</li>
<li><em>n</em> <span class="math inline">\(\to\)</span> número total de elementos em uma amostra</li>
<li><em>X</em> <span class="math inline">\(\to\)</span> número de elementos na população que possui determinada característica</li>
<li><em>x</em> <span class="math inline">\(\to\)</span> número de elementos na amostra que possui determinada característica</li>
</ul>
<p>Como no caso da média, a diferença entre a proporção amostral e a proporção populacional correspondente, determina o <em>erro amostral</em>, assumindo que a amostra é aleatória e nenhum erro não amostral foi cometido. Ou seja,</p>
<p><span class="math display">\[
erro \quad amostral = \hat{p} - p
\]</span></p>
<p>A <strong>distribuição amostral de uma proporção</strong> é a distribuição das proporções de todas as amostras possíveis de tamanho <em>n</em> retiradas de uma população.</p>
<p>De acordo com o Teorema Central do Limite, para amostras suficientemente grandes, a distribuição de <span class="math inline">\(\hat{p}\)</span> se aproxima de uma distribuição normal, mesmo que os dados originais sejam binomiais (sucesso/fracasso), desde que: <span class="math inline">\(np \geq 5\)</span> e <span class="math inline">\(n(1 - p) \geq 5\)</span>.</p>
<p>Assim,</p>
<p><span class="math display">\[E(\hat{p})=\mu_\hat{p}\]</span></p>
<p><span class="math display">\[Var(\hat{p})=\sigma^2_\hat{p}=\frac{\hat{p}(1-\hat{p})}{n}\]</span> Logo,</p>
<p><span class="math display">\[E(\hat{p})=\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p>Dessa forma, a distribuição amostral de <span class="math inline">\(\hat{p}\)</span> será:</p>
<p><span class="math display">\[
\hat{p} \sim N(\hat{p}, \frac{\hat{p}(1-\hat{p})}{n})
\]</span></p>
<p>Quando não conhecemos a proporção populacional <em>p</em>, pode-se usar <span class="math inline">\(\hat{p}\)</span> como estimativa dessa proporção, desde que as condições acima sejam satisfeitas.</p>
<p>Dessa forma, pode-se calcular probabilidades aproximadas por uma distribuição normal com média <span class="math inline">\(μ = n \times p\)</span> e <span class="math inline">\(σ = \sqrt{(n×p(1-p))}\)</span> (veja também <a href="09-probabilidades.html#sec-mudpbinom" class="quarto-xref"><span>Seção 9.8.2</span></a>).</p>
<p>Considerando a “população”, usada neste capítulo, o conjunto de dados <code>dadosMater.xlsx</code>, será verificado a proporção de mulheres fumantes. Inicialmente, a variável <code>fumo</code>, que está como variável numérica, será transformada em fator:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(fumo) <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fumo =</span> <span class="fu">factor</span>(fumo, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Fumante"</span>, <span class="st">"Não fumante"</span>)))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A proporção de fumantes, frequência relativa (<em>fr</em>) é:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fumo <span class="ot">&lt;-</span> <span class="fu">with</span>(dados, <span class="fu">table</span>(fumo))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>fr.fumo <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(fumo)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>fr.fumo</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fumo
    Fumante Não fumante 
  0.2200292   0.7799708 </code></pre>
</div>
</div>
<p>A saída retorna que a proporção de fumantes entre as mulheres desse arquivo é 0.22. Esta será considerada a proporção <em>p</em> da ‘população’. Agora, imagine que esse resultado fosse desconhecido. Então, para saber a qual a proporção de fumantes dessa ‘população’, seria necessário extrair uma amostra adequada. Foi selecionada uma amostra de n = 100 da ‘população’ alvo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">set.seed</span>(<span class="dv">134</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a> amostra.fumo <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">100</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Usando a <code>amostra.fumo</code>, calcula-se a proporção de fumantes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a> tabagismo <span class="ot">&lt;-</span> <span class="fu">with</span>(amostra.fumo, <span class="fu">table</span>(fumo))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a> fr <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(tabagismo)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a> fp <span class="ot">&lt;-</span> fr<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a> tab.fumo <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">n =</span> tabagismo,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fr =</span> <span class="fu">round</span>(fr, <span class="dv">2</span>),</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fp =</span> <span class="fu">round</span>(fp, <span class="dv">2</span>))</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a> tab.fumo</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             n  fr fp
Fumante     20 0.2 20
Não fumante 80 0.8 80</code></pre>
</div>
</div>
<p>A proporção de uma amostra é uma variável aleatória: varia de amostra para amostra de uma forma que não pode ser prevista com certeza. O Teorema Central do Limite se aplica em proporções. À medida que novas amostras forem extraídas, o valor da proporção amostral <span class="math inline">\(\hat{p}\)</span> se aproxima da proporção populacional <em>p</em>. Na “população” <em>p</em> = 0,22; na amostra de n = 100, <span class="math inline">\(\hat{p}\)</span> = 0.2. Para amostras grandes, a proporção amostral tem distribuição aproximadamente normal com as seguinte características mencionadas acima em relação a <span class="math inline">\(\mu_\hat{p}\)</span> e <span class="math inline">\(\sigma_\hat{p}\)</span>.<br>
Como verificar se uma amostra é grande?</p>
<p>Uma amostra é grande se o intervalo</p>
<p><span class="math display">\[
[\hat{p}-3 \times \sigma_\hat{p} , \quad \hat{p}-3 \times \sigma_\hat{p}]
\]</span></p>
<p>estiver totalmente dentro do intervalo [0,1].</p>
<p>Na prática, <em>p</em> não é conhecido, portanto, <span class="math inline">\(\sigma_\hat{p}\)</span> também não é. Nesse caso, para verificar se a amostra é suficientemente grande, substitui-se o valor de <em>p</em> pelo valor conhecido de <span class="math inline">\(\hat{p}\)</span>. Isso significa verificar se o intervalo</p>
<p><span class="math display">\[
\hat{p}-3\times\sqrt{\frac{\hat{p}(1-\hat{p})}{n}},\quad \hat{p}+3\times\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}
\]</span></p>
<p>encontra-se totalmente dentro do intervalo [0,1].</p>
<p>Transportando os dados da amostra de gestantes, para a fórmula e usando o <em>R</em> para o cálculo, tem-se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>p.chapeu <span class="ot">&lt;-</span> tab.fumo[<span class="dv">1</span>,<span class="dv">2</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> tab.fumo[<span class="dv">1</span>,<span class="dv">1</span>] <span class="sc">+</span> tab.fumo[<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>li <span class="ot">&lt;-</span> p.chapeu <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>ls <span class="ot">&lt;-</span> p.chapeu <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(li, ls), <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08 0.32</code></pre>
</div>
</div>
<p>Como os limites ficam no intervalo [0, 1], chega-se à conclusão de que a amostra de <em>n</em> = 100 é aceitável para estimar a proporção populacional.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercício
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uma amostra com tamanho n = 40 é suficiente?</p>
</div>
</div>
<p><u>Resposta</u>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">40</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>li <span class="ot">&lt;-</span> p.chapeu <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n) </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>ls <span class="ot">&lt;-</span> p.chapeu <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(li, ls), <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0103 0.3897</code></pre>
</div>
</div>
<p>Sim, é aceitável uma amostra de n = 40.</p>


<!-- -->

<div id="refs" class="references csl-bib-body" role="list" style="display: none">
<div id="ref-pagano2000sampling" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Pagano M, Gavreau K. The Central Limit Theorem. Em: Principles of Biostatistics. Second Edition. Pacific Grove, CA: Duxbury; 2000. p. 197–8. </div>
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Para que a cada nova amostragem retorne o mesmo conjunto de dados, é usado a função <code>set.seed()</code>(veja <a href="09-probabilidades.html#sec-rnorm" class="quarto-xref"><span>Seção 9.7.2.4</span></a>)<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Observe que o número da “semente” foi modificado para 236. Poderia ser qualquer outro número, isto garante que o sorteio seja diferente, mas ainda reprodutível.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Salários mínimos<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./10-assimetria.html" class="pagination-link" aria-label="Assimetria e Curtose">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Assimetria e Curtose</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./12-estimacao.html" class="pagination-link" aria-label="Estimação">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Estimação</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb32" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Distribuições Amostrais {#sec-cap11}</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pacotes necessários para este capítulo</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>               e1071, </span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>               ggplot2, </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>               knitr, </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>               readxl)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## Distribuições populacional e amostral</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>Métricas como a média, a mediana e o desvio padrão são medidas numéricas de resumo. Quando calculadas a partir de dados de uma amostra são denominadas **estatísticas amostrais**. Por outro lado, as mesmas medidas numéricas de resumo calculadas para dados populacionais são chamadas de **parâmetros populacionais**.</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>Um parâmetro populacional é sempre uma constante, enquanto uma estatística de amostra é sempre uma variável aleatória. Como cada variável aleatória deve possuir uma distribuição de probabilidade, cada estatística de amostra possui uma distribuição de probabilidade. A distribuição de probabilidade de uma estatística de amostra é mais comumente chamada de **distribuição amostral**. Os conceitos abordados neste capítulo são a base da **estatística inferencial**.</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="fu">### Distribuição populacional</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>A distribuição populacional é a distribuição de probabilidade derivada das informações sobre todos os elementos de uma **população**.</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>Para fins de raciocínio didático, o conjunto de dados de 1368 observações de puérperas e recém-nascidos da Maternidade-escola do Hospital Geral de Caxias do Sul, RS, será considerado uma população. O gráfico da @fig-histbxp, da @sec-assimetria, mostra a distribuição da <span class="in">`altura`</span> das puérperas dessa ‘população’. Os parâmetros ($\mu$ e $\sigma$) dessa "*população*" são:</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(altura)</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a> media <span class="ot">=</span> <span class="fu">mean</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a> <span class="fu">round</span>(media, <span class="dv">3</span>)</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a> dp <span class="ot">=</span> <span class="fu">sd</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a> <span class="fu">round</span>(dp, <span class="dv">3</span>)</span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a><span class="fu">### Distribuição amostral {#sec-dam}</span></span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>Conforme mencionado no início deste capítulo, o valor de um parâmetro da população é sempre constante. Por exemplo, para qualquer conjunto de dados populacionais, há apenas um valor para a média populacional, $\mu$.</span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>No entanto, não se pode dizer o mesmo sobre a média amostral. Amostras diferentes do mesmo tamanho, retiradas da mesma população, produzem valores diferentes da média amostral, $\bar{x}$. O valor da média amostral, para qualquer amostra, dependerá dos elementos incluídos nessa amostra. Em decorrência, a média amostral é uma variável aleatória. Portanto, como outras variáveis aleatórias, a média amostral possui uma distribuição de probabilidade, que é mais comumente chamada de **distribuição amostral da média**.</span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a>Outras estatísticas de amostra, como mediana, moda e desvio padrão, também possuem distribuições amostrais. Em geral, a distribuição de probabilidades de uma amostra é denominada de **distribuição amostral**.</span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a>Usar a variável <span class="in">`altura`</span> das puérperas da Maternidade do HGCS como a população de interesse é apenas uma estratégia didática. Raramente, na vida real, é possível obter dados da população inteira. Reunir essa informação costuma ser muito custoso ou impossível. Por essa razão, a prática é selecionar apenas uma amostra da população e a usar para compreender as suas características.</span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a>A função <span class="in">`slice_sample()`</span> do pacote <span class="in">`dplyr`</span>extrairá uma amostra <span class="ot">[^11-distamostrais-1]</span> de n = 30 da população. As funções <span class="in">`mean()`</span> e <span class="in">`sd()`</span> calcularão a média e o desvio padrão, repectivamente:</span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a><span class="ot">[^11-distamostrais-1]: </span>Para que a cada nova amostragem retorne o mesmo conjunto de dados, é usado a função <span class="in">`set.seed()`</span>(veja @sec-rnorm)</span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-55"><a href="#cb32-55" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-56"><a href="#cb32-56" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb32-57"><a href="#cb32-57" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb32-58"><a href="#cb32-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-59"><a href="#cb32-59" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">234</span>)</span>
<span id="cb32-60"><a href="#cb32-60" aria-hidden="true" tabindex="-1"></a>amostra1 <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb32-61"><a href="#cb32-61" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb32-62"><a href="#cb32-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-63"><a href="#cb32-63" aria-hidden="true" tabindex="-1"></a>media1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra1<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb32-64"><a href="#cb32-64" aria-hidden="true" tabindex="-1"></a>dp1 <span class="ot">&lt;-</span>  <span class="fu">sd</span>(amostra1<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb32-65"><a href="#cb32-65" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(media1, dp1))</span>
<span id="cb32-66"><a href="#cb32-66" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-67"><a href="#cb32-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-68"><a href="#cb32-68" aria-hidden="true" tabindex="-1"></a>Se este processo for repetido várias vezes, a cada amostra aleatória <span class="ot">[^11-distamostrais-2]</span>, serão gerados médias e desvios padrão diferentes.</span>
<span id="cb32-69"><a href="#cb32-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-70"><a href="#cb32-70" aria-hidden="true" tabindex="-1"></a><span class="ot">[^11-distamostrais-2]: </span>Observe que o número da "semente" foi modificado para 236. Poderia ser qualquer outro número, isto garante que o sorteio seja diferente, mas ainda reprodutível.</span>
<span id="cb32-71"><a href="#cb32-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-74"><a href="#cb32-74" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-75"><a href="#cb32-75" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb32-76"><a href="#cb32-76" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb32-77"><a href="#cb32-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-78"><a href="#cb32-78" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">236</span>)</span>
<span id="cb32-79"><a href="#cb32-79" aria-hidden="true" tabindex="-1"></a>amostra2 <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb32-80"><a href="#cb32-80" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb32-81"><a href="#cb32-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-82"><a href="#cb32-82" aria-hidden="true" tabindex="-1"></a>media2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra2<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb32-83"><a href="#cb32-83" aria-hidden="true" tabindex="-1"></a>dp2 <span class="ot">&lt;-</span>  <span class="fu">sd</span>(amostra2<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb32-84"><a href="#cb32-84" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(media2, dp2))</span>
<span id="cb32-85"><a href="#cb32-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-86"><a href="#cb32-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-87"><a href="#cb32-87" aria-hidden="true" tabindex="-1"></a>À medida que o número de amostras possíveis forem aumentando, elas constituem uma distribuição cuja média, média das médias, $\bar{x}_{\bar{x}}$, é igual a média populacional, $\mu$. Essa distribuição, no caso da média, recebe o nome de **distribuição amostral das médias**.</span>
<span id="cb32-88"><a href="#cb32-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-89"><a href="#cb32-89" aria-hidden="true" tabindex="-1"></a>Agora, para exemplificar este conceito, serão geradas 5000 amostras e calculada a média de cada uma das amostras de n = 30 que constituirão a distribuição, mostrada no gráfico da @fig-dam.</span>
<span id="cb32-90"><a href="#cb32-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-93"><a href="#cb32-93" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-94"><a href="#cb32-94" aria-hidden="true" tabindex="-1"></a><span class="co"># extraindo 5000 amostras</span></span>
<span id="cb32-95"><a href="#cb32-95" aria-hidden="true" tabindex="-1"></a>amostras5000 <span class="ot">&lt;-</span> <span class="fu">rep</span> (<span class="dv">0</span>, <span class="dv">5000</span>)</span>
<span id="cb32-96"><a href="#cb32-96" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5000</span>) {</span>
<span id="cb32-97"><a href="#cb32-97" aria-hidden="true" tabindex="-1"></a>  amostra <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">slice_sample</span> (<span class="at">n =</span> <span class="dv">30</span>) </span>
<span id="cb32-98"><a href="#cb32-98" aria-hidden="true" tabindex="-1"></a>  amostras5000 [i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra<span class="sc">$</span>altura)</span>
<span id="cb32-99"><a href="#cb32-99" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-100"><a href="#cb32-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-101"><a href="#cb32-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-102"><a href="#cb32-102" aria-hidden="true" tabindex="-1"></a>Media e desvio padrão das 5000 amostras:</span>
<span id="cb32-103"><a href="#cb32-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-106"><a href="#cb32-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-107"><a href="#cb32-107" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">mean</span> (amostras5000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb32-108"><a href="#cb32-108" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">sd</span> (amostras5000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb32-109"><a href="#cb32-109" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(mu, sigma))</span>
<span id="cb32-110"><a href="#cb32-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-111"><a href="#cb32-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-114"><a href="#cb32-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-115"><a href="#cb32-115" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-dam</span></span>
<span id="cb32-116"><a href="#cb32-116" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-117"><a href="#cb32-117" aria-hidden="true" tabindex="-1"></a><span class="co">#| out.width: "70%"</span></span>
<span id="cb32-118"><a href="#cb32-118" aria-hidden="true" tabindex="-1"></a><span class="co">#| out.height: "70%"</span></span>
<span id="cb32-119"><a href="#cb32-119" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.align: 'center'</span></span>
<span id="cb32-120"><a href="#cb32-120" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.cap: "Distribuição amostral das médias de 5000 amostras de n = 30"</span></span>
<span id="cb32-121"><a href="#cb32-121" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb32-122"><a href="#cb32-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-123"><a href="#cb32-123" aria-hidden="true" tabindex="-1"></a>amostras5000 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(amostras5000)</span>
<span id="cb32-124"><a href="#cb32-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-125"><a href="#cb32-125" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> amostras5000)<span class="sc">+</span> </span>
<span id="cb32-126"><a href="#cb32-126" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> amostras5000,</span>
<span id="cb32-127"><a href="#cb32-127" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb32-128"><a href="#cb32-128" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb32-129"><a href="#cb32-129" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb32-130"><a href="#cb32-130" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span><span class="st">"tomato"</span>) <span class="sc">+</span></span>
<span id="cb32-131"><a href="#cb32-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>dnorm,</span>
<span id="cb32-132"><a href="#cb32-132" aria-hidden="true" tabindex="-1"></a>                <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span>mu,<span class="at">sd=</span>sigma), </span>
<span id="cb32-133"><a href="#cb32-133" aria-hidden="true" tabindex="-1"></a>                <span class="at">col=</span><span class="st">'dodgerblue4'</span>,</span>
<span id="cb32-134"><a href="#cb32-134" aria-hidden="true" tabindex="-1"></a>                <span class="at">lwd=</span><span class="dv">1</span>,</span>
<span id="cb32-135"><a href="#cb32-135" aria-hidden="true" tabindex="-1"></a>                <span class="at">lty=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb32-136"><a href="#cb32-136" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Densidade de Probabilidade"</span>,</span>
<span id="cb32-137"><a href="#cb32-137" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Altura das parturientes (m)"</span>) <span class="sc">+</span></span>
<span id="cb32-138"><a href="#cb32-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span>
<span id="cb32-139"><a href="#cb32-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-140"><a href="#cb32-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-141"><a href="#cb32-141" aria-hidden="true" tabindex="-1"></a>Se a média, $\bar{x}_{\bar{x}}$, dessas 5000 amostras de n = 30, for comparada com a média populacional, $\mu$, observa-se que até 3 dígitos decimais não há uma diferença. Entretanto, o desvio padrão é bem menor (<span class="in">`r round (sigma,  3)`</span>) que o da população (<span class="in">`r round(dp, 3)`</span>).</span>
<span id="cb32-142"><a href="#cb32-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-143"><a href="#cb32-143" aria-hidden="true" tabindex="-1"></a><span class="fu">## Erros amostrais e não amostrais</span></span>
<span id="cb32-144"><a href="#cb32-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-145"><a href="#cb32-145" aria-hidden="true" tabindex="-1"></a>Amostras diferentes selecionadas da mesma população darão resultados diferentes porque contêm elementos diferentes. Isso é evidente nas medias das amostra1 e amostra2, <span class="in">`r round(mean(amostra1$altura, na.rm =TRUE), 3)`</span>m e <span class="in">`r round(mean(amostra2$altura, na.rm =TRUE), 3)`</span>m, respectivamente, comparadas com a média da população igual a <span class="in">`r round(mean(dados$altura, na.rm =TRUE), 3)`</span>m .</span>
<span id="cb32-146"><a href="#cb32-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-149"><a href="#cb32-149" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-150"><a href="#cb32-150" aria-hidden="true" tabindex="-1"></a>erro1 <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">mean</span>(amostra1<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">mean</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>))</span>
<span id="cb32-151"><a href="#cb32-151" aria-hidden="true" tabindex="-1"></a>erro2 <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">mean</span>(amostra2<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">mean</span>(dados<span class="sc">$</span>altura, <span class="at">na.rm =</span><span class="cn">TRUE</span>))</span>
<span id="cb32-152"><a href="#cb32-152" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(erro1, erro2), <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb32-153"><a href="#cb32-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-154"><a href="#cb32-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-155"><a href="#cb32-155" aria-hidden="true" tabindex="-1"></a>Se outras amostras forem extraídas, o resultado obtido de qualquer amostra geralmente será diferente do resultado obtido da população correspondente. A diferença entre o valor de uma estatística amostral obtida de uma amostra e o valor do parâmetro populacional correspondente, é chamado de **erro amostral**. Observe que essa diferença representa o erro amostral apenas se a amostra for aleatória e não houver nenhum erro não amostral. Caso contrário, apenas uma parte dessa diferença será devido ao erro amostral.</span>
<span id="cb32-156"><a href="#cb32-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-157"><a href="#cb32-157" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-158"><a href="#cb32-158" aria-hidden="true" tabindex="-1"></a> erro \quad amostral = \bar{x}_{i} - \mu  </span>
<span id="cb32-159"><a href="#cb32-159" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-160"><a href="#cb32-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-161"><a href="#cb32-161" aria-hidden="true" tabindex="-1"></a>É importante lembrar que o erro amostral ocorre devido ao acaso. Não é possível evitar o erro amostral. É possível limitar o seu valor através da seleção de uma amostra adequada. Os erros que ocorrem por outros motivos, como erros cometidos durante a coleta, registro e tabulação dos dados, são chamados de **erros não amostrais**. Esses erros ocorrem, em geral, por causa de erros humanos e não por acaso.</span>
<span id="cb32-162"><a href="#cb32-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-163"><a href="#cb32-163" aria-hidden="true" tabindex="-1"></a><span class="fu">## Média e desvio padrão da média</span></span>
<span id="cb32-164"><a href="#cb32-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-165"><a href="#cb32-165" aria-hidden="true" tabindex="-1"></a>A média e o desvio padrão calculados para a distribuição amostral da média são chamados de *média (*$\mu_{\bar{x}}$) e *desvio padrão (*$\sigma_{\bar{x}}$) da média. Na verdade, a média e o desvio padrão da média são, respectivamente, a média e o desvio padrão das médias de todas as amostras do mesmo tamanho selecionadas de uma população. O desvio padrão da média é, comumente, chamado de **erro padrão da média** ($\sigma_{\bar{x}}$).</span>
<span id="cb32-166"><a href="#cb32-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-167"><a href="#cb32-167" aria-hidden="true" tabindex="-1"></a>A média amostral, $\bar{x}$, é chamada de *estimador* da média da população, $\mu$. Quando o valor esperado (ou média) de uma estatística amostral é igual ao valor do parâmetro populacional correspondente, essa estatística amostral é considerada um estimador não enviesado, consistente.\</span>
<span id="cb32-168"><a href="#cb32-168" aria-hidden="true" tabindex="-1"></a>Para a média amostral $\bar{x}$, $\mu_{\bar{x}} = \mu$. Logo, $\bar{x}$, é um estimador imparcial de $\mu$. Esta é uma propriedade muito importante que um estimador deve possuir. No entanto, o desvio padrão da média, $\sigma_{\bar{x}}$, não é igual ao desvio padrão, $\sigma$, da distribuição populacional (a menos que n = 1). O desvio padrão da média amostral é igual ao desvio padrão da população dividido pela raiz quadrada do tamanho amostral:</span>
<span id="cb32-169"><a href="#cb32-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-170"><a href="#cb32-170" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-171"><a href="#cb32-171" aria-hidden="true" tabindex="-1"></a>\sigma_{\bar{x}} = \frac {\sigma}{\sqrt{n}}</span>
<span id="cb32-172"><a href="#cb32-172" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-173"><a href="#cb32-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-174"><a href="#cb32-174" aria-hidden="true" tabindex="-1"></a>A dispersão da distribuição amostral da média é menor do que dispersão da distribuição populacional correspondente, como mostrado acima. Em outras palavras, $\sigma_{\bar{x}} &lt; \sigma$. Isso é visível na fórmula do $\sigma_{\bar{x}}$ . Quando *n* é maior que 1, o que geralmente é verdadeiro, o denominador em $\frac {\sigma}{\sqrt{n}}$ é maior que 1. Desta forma, $\sigma_{\bar{x}}$ é menor que $\sigma$. O desvio padrão da distribuição amostral da média diminui à medida que o tamanho amostral aumenta.</span>
<span id="cb32-175"><a href="#cb32-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-176"><a href="#cb32-176" aria-hidden="true" tabindex="-1"></a>Sempre que o *n* for grande, em geral \&gt; 30 @pagano2000sampling, pode ser assumido que a distribuição será uma curva normal e que o desvio padrão da amostra (*s*) é um estimador não enviesado do desvio padrão populacional ($\sigma$). Então, o erro padrão da média ($\sigma_{\bar{x}}$) pode ser estimado pelo $EP_{\bar{x}}$:</span>
<span id="cb32-177"><a href="#cb32-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-178"><a href="#cb32-178" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-179"><a href="#cb32-179" aria-hidden="true" tabindex="-1"></a>EP_{\bar{x}} = \frac {s}{\sqrt{n}}</span>
<span id="cb32-180"><a href="#cb32-180" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-181"><a href="#cb32-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-182"><a href="#cb32-182" aria-hidden="true" tabindex="-1"></a><span class="fu">## Teorema do Limite Central (TCL) {#sec-tcl}</span></span>
<span id="cb32-183"><a href="#cb32-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-184"><a href="#cb32-184" aria-hidden="true" tabindex="-1"></a>Na maioria das vezes, a população da qual as amostras são extraídas não é normalmente distribuída. Em tais casos, a forma da distribuição amostral de X é inferida de um teorema muito importante chamado *teorema do limite central*. De acordo com este teorema para um grande tamanho de amostra (em geral, acima de 30), a distribuição amostral da média é aproximadamente normal, independentemente da forma da distribuição da população @pagano2000sampling. Esta aproximação tornar-se-á mais acurada à medida que aumenta o tamanho amostral:</span>
<span id="cb32-185"><a href="#cb32-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-186"><a href="#cb32-186" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>a média da distribuição amostral, $\mu_{\bar{x}}$, é igual a média populacional, $\mu$;</span>
<span id="cb32-187"><a href="#cb32-187" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>desvio padrão da distribuição amostral, $\sigma_{\bar{x}}$, é igual a $\frac {\sigma}{\sqrt{n}}$;</span>
<span id="cb32-188"><a href="#cb32-188" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>o erro padrão da média, $\sigma_{\bar{x}}$, é sempre menor (@fig-standard) que o desvio padrão populacional, $\sigma$.</span>
<span id="cb32-189"><a href="#cb32-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-192"><a href="#cb32-192" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-193"><a href="#cb32-193" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-standard</span></span>
<span id="cb32-194"><a href="#cb32-194" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-195"><a href="#cb32-195" aria-hidden="true" tabindex="-1"></a><span class="co">#| out.width: "70%"</span></span>
<span id="cb32-196"><a href="#cb32-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.align: 'center'</span></span>
<span id="cb32-197"><a href="#cb32-197" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.cap: "Erro padrão versus desvio padrão"</span></span>
<span id="cb32-198"><a href="#cb32-198" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb32-199"><a href="#cb32-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-200"><a href="#cb32-200" aria-hidden="true" tabindex="-1"></a> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"https://i.imgur.com/I2CxksB.png"</span>)</span>
<span id="cb32-201"><a href="#cb32-201" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-202"><a href="#cb32-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-203"><a href="#cb32-203" aria-hidden="true" tabindex="-1"></a><span class="fu">### Exemplo com uma variável assimétrica</span></span>
<span id="cb32-204"><a href="#cb32-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-205"><a href="#cb32-205" aria-hidden="true" tabindex="-1"></a>Como exemplo, será explorada a variável <span class="in">`renda`</span>, do conjunto de dados <span class="in">`dadosMater.xlsx`</span>, que representa a renda familiar em salários mínimos (*sm*). Como foi feito anteriormente, suponha que essa variável seja a "população" de estudo. Ela tem as seguintes medidas resumidoras e de assimetria:</span>
<span id="cb32-206"><a href="#cb32-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-209"><a href="#cb32-209" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-210"><a href="#cb32-210" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>)</span>
<span id="cb32-211"><a href="#cb32-211" aria-hidden="true" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> </span>
<span id="cb32-212"><a href="#cb32-212" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (renda) <span class="sc">%&gt;%</span> </span>
<span id="cb32-213"><a href="#cb32-213" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span> (<span class="at">media.sm =</span> <span class="fu">mean</span> (dados<span class="sc">$</span>renda, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-214"><a href="#cb32-214" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dp.sm =</span> <span class="fu">sd</span>(dados<span class="sc">$</span>renda, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-215"><a href="#cb32-215" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mediana.sm =</span> <span class="fu">median</span>(dados<span class="sc">$</span>renda, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-216"><a href="#cb32-216" aria-hidden="true" tabindex="-1"></a>                    <span class="at">assimetria =</span> e1071<span class="sc">::</span><span class="fu">skewness</span>(dados<span class="sc">$</span>renda),</span>
<span id="cb32-217"><a href="#cb32-217" aria-hidden="true" tabindex="-1"></a>                    <span class="at">curtose =</span> e1071<span class="sc">::</span><span class="fu">kurtosis</span>(dados<span class="sc">$</span>renda))</span>
<span id="cb32-218"><a href="#cb32-218" aria-hidden="true" tabindex="-1"></a>resumo</span>
<span id="cb32-219"><a href="#cb32-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-220"><a href="#cb32-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-221"><a href="#cb32-221" aria-hidden="true" tabindex="-1"></a>O desvio padrão é grande em relação à média, com um coeficiente de variação de <span class="in">`r round(resumo$dp.sm/resumo$media.sm, 3)*100`</span>% e uma mediana <span class="sc">\&lt;</span> média. Estas métricas junto com os coeficientes de assimetria e curtose apontam para a assimetria positiva da variável <span class="in">`renda`</span>. O gráfico da @fig-skewpos confirma esta afirmação:</span>
<span id="cb32-222"><a href="#cb32-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-225"><a href="#cb32-225" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-226"><a href="#cb32-226" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-skewpos</span></span>
<span id="cb32-227"><a href="#cb32-227" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-228"><a href="#cb32-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| out.width: "70%"</span></span>
<span id="cb32-229"><a href="#cb32-229" aria-hidden="true" tabindex="-1"></a><span class="co">#| out.height: "70%"</span></span>
<span id="cb32-230"><a href="#cb32-230" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.align: 'center'</span></span>
<span id="cb32-231"><a href="#cb32-231" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.cap: "Distribuição assimétrica positiva"</span></span>
<span id="cb32-232"><a href="#cb32-232" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb32-233"><a href="#cb32-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-234"><a href="#cb32-234" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dados)<span class="sc">+</span> </span>
<span id="cb32-235"><a href="#cb32-235" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> renda,</span>
<span id="cb32-236"><a href="#cb32-236" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb32-237"><a href="#cb32-237" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb32-238"><a href="#cb32-238" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col =</span> <span class="st">"white"</span>,</span>
<span id="cb32-239"><a href="#cb32-239" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span><span class="st">"darkolivegreen4"</span>) <span class="sc">+</span></span>
<span id="cb32-240"><a href="#cb32-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>dnorm,</span>
<span id="cb32-241"><a href="#cb32-241" aria-hidden="true" tabindex="-1"></a>                <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span>resumo<span class="sc">$</span>media.sm,<span class="at">sd=</span>resumo<span class="sc">$</span>dp.sm), </span>
<span id="cb32-242"><a href="#cb32-242" aria-hidden="true" tabindex="-1"></a>                <span class="at">col=</span><span class="st">'red'</span>,</span>
<span id="cb32-243"><a href="#cb32-243" aria-hidden="true" tabindex="-1"></a>                <span class="at">lwd=</span><span class="dv">1</span>,</span>
<span id="cb32-244"><a href="#cb32-244" aria-hidden="true" tabindex="-1"></a>                <span class="at">lty=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb32-245"><a href="#cb32-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Densidade de Probabilidade"</span>,</span>
<span id="cb32-246"><a href="#cb32-246" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Renda Familiar em SM"</span>) <span class="sc">+</span></span>
<span id="cb32-247"><a href="#cb32-247" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-248"><a href="#cb32-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-249"><a href="#cb32-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-250"><a href="#cb32-250" aria-hidden="true" tabindex="-1"></a>Os valores da média e do desvio padrão calculados para a distribuição de probabilidade dessa população fornecem os valores dos parâmetros populacionais $\mu$ e $\sigma$. Esses valores são $\mu$ =<span class="in">`r round(resumo$media.sm, 2)`</span> *sm* [^11-distamostrais-3] e $\sigma$ =`r round(resumo$dp.sm, 2)` *sm*.\</span>
<span id="cb32-251"><a href="#cb32-251" aria-hidden="true" tabindex="-1"></a>Se extrairmos múltiplas amostras dessa população, observa-se a modificação do formato da distribuição à medida que aumenta o tamanho amostral, se aproximando progressivamente do modelo normal, com um número grande de amostras.</span>
<span id="cb32-252"><a href="#cb32-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-253"><a href="#cb32-253" aria-hidden="true" tabindex="-1"></a><span class="ot">[^11-distamostrais-3]: </span>Salários mínimos</span>
<span id="cb32-254"><a href="#cb32-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-255"><a href="#cb32-255" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Extração de múltiplas amostras(1000)</span><span class="co">]</span>{.underline}</span>
<span id="cb32-256"><a href="#cb32-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-259"><a href="#cb32-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-260"><a href="#cb32-260" aria-hidden="true" tabindex="-1"></a>amostras1000 <span class="ot">&lt;-</span> <span class="fu">rep</span> (<span class="dv">0</span>, <span class="dv">1000</span>)</span>
<span id="cb32-261"><a href="#cb32-261" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb32-262"><a href="#cb32-262" aria-hidden="true" tabindex="-1"></a>  amostra.sm <span class="ot">&lt;-</span> <span class="fu">sample</span> (dados<span class="sc">$</span>renda, <span class="dv">30</span>) </span>
<span id="cb32-263"><a href="#cb32-263" aria-hidden="true" tabindex="-1"></a>  amostras1000 [i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(amostra.sm)</span>
<span id="cb32-264"><a href="#cb32-264" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-265"><a href="#cb32-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-266"><a href="#cb32-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-267"><a href="#cb32-267" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Media e desvio padrão das 1000 amostras</span><span class="co">]</span>{.underline}</span>
<span id="cb32-268"><a href="#cb32-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-271"><a href="#cb32-271" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-272"><a href="#cb32-272" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">mean</span> (amostras1000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb32-273"><a href="#cb32-273" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">sd</span> (amostras1000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb32-274"><a href="#cb32-274" aria-hidden="true" tabindex="-1"></a>md <span class="ot">&lt;-</span> <span class="fu">round</span> (<span class="fu">median</span>(amostras1000), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb32-275"><a href="#cb32-275" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(mu, sigma, md))</span>
<span id="cb32-276"><a href="#cb32-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-277"><a href="#cb32-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-278"><a href="#cb32-278" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Assimetria e curtose</span><span class="co">]</span>{.underline}</span>
<span id="cb32-279"><a href="#cb32-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-282"><a href="#cb32-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-283"><a href="#cb32-283" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> e1071<span class="sc">::</span><span class="fu">skewness</span>(amostras1000)</span>
<span id="cb32-284"><a href="#cb32-284" aria-hidden="true" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> e1071<span class="sc">::</span><span class="fu">kurtosis</span>(amostras1000)</span>
<span id="cb32-285"><a href="#cb32-285" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(b1, b2))</span>
<span id="cb32-286"><a href="#cb32-286" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-287"><a href="#cb32-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-290"><a href="#cb32-290" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-291"><a href="#cb32-291" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-semskew</span></span>
<span id="cb32-292"><a href="#cb32-292" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-293"><a href="#cb32-293" aria-hidden="true" tabindex="-1"></a><span class="co">#| out.width: "70%"</span></span>
<span id="cb32-294"><a href="#cb32-294" aria-hidden="true" tabindex="-1"></a><span class="co">#| out.height: "70%"</span></span>
<span id="cb32-295"><a href="#cb32-295" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.align: 'center'</span></span>
<span id="cb32-296"><a href="#cb32-296" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.cap: "Distribuição praticamente normal"</span></span>
<span id="cb32-297"><a href="#cb32-297" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb32-298"><a href="#cb32-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-299"><a href="#cb32-299" aria-hidden="true" tabindex="-1"></a>amostras1000 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(amostras1000)</span>
<span id="cb32-300"><a href="#cb32-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-301"><a href="#cb32-301" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> amostras1000)<span class="sc">+</span> </span>
<span id="cb32-302"><a href="#cb32-302" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> amostras1000,</span>
<span id="cb32-303"><a href="#cb32-303" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb32-304"><a href="#cb32-304" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb32-305"><a href="#cb32-305" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col =</span> <span class="st">"white"</span>,</span>
<span id="cb32-306"><a href="#cb32-306" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span><span class="st">"darkolivegreen4"</span>) <span class="sc">+</span></span>
<span id="cb32-307"><a href="#cb32-307" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>dnorm,</span>
<span id="cb32-308"><a href="#cb32-308" aria-hidden="true" tabindex="-1"></a>                <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="fu">mean</span>(amostras1000<span class="sc">$</span>amostras1000),<span class="at">sd=</span><span class="fu">sd</span>(amostras1000<span class="sc">$</span>amostras1000)), </span>
<span id="cb32-309"><a href="#cb32-309" aria-hidden="true" tabindex="-1"></a>                <span class="at">col=</span><span class="st">'red'</span>,</span>
<span id="cb32-310"><a href="#cb32-310" aria-hidden="true" tabindex="-1"></a>                <span class="at">lwd=</span><span class="dv">1</span>,</span>
<span id="cb32-311"><a href="#cb32-311" aria-hidden="true" tabindex="-1"></a>                <span class="at">lty=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb32-312"><a href="#cb32-312" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Densidade de Probabilidade"</span>,</span>
<span id="cb32-313"><a href="#cb32-313" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Renda Familiar em SM"</span>) <span class="sc">+</span></span>
<span id="cb32-314"><a href="#cb32-314" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-315"><a href="#cb32-315" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-316"><a href="#cb32-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-317"><a href="#cb32-317" aria-hidden="true" tabindex="-1"></a>Ou seja, extraindo-se 1000 amostras de n = 30 e calculando as mesmas métricas anteriores, observa-se que, embora a distribuição populacional original seja assimétrica, a distribuição amostral da média se aproxima bastante da distribuição gaussiana (@fig-semskew).</span>
<span id="cb32-318"><a href="#cb32-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-319"><a href="#cb32-319" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb32-320"><a href="#cb32-320" aria-hidden="true" tabindex="-1"></a><span class="fu">## Importância do Teorema do Limite Central</span></span>
<span id="cb32-321"><a href="#cb32-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-322"><a href="#cb32-322" aria-hidden="true" tabindex="-1"></a>O TCL é um dos pilares da inferência estatística. Entender a sua importância é como destrancar a porta para aplicar testes, construir intervalos de confiança e fazer previsões com segurança, mesmo quando os dados parecem confusos.</span>
<span id="cb32-323"><a href="#cb32-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-324"><a href="#cb32-324" aria-hidden="true" tabindex="-1"></a>O TCL afirma que:</span>
<span id="cb32-325"><a href="#cb32-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-326"><a href="#cb32-326" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; A distribuição das médias amostrais tende a ser normal, mesmo que a população original não seja, desde que o tamanho da amostra seja suficientemente grande.</span></span>
<span id="cb32-327"><a href="#cb32-327" aria-hidden="true" tabindex="-1"></a><span class="at">:::</span></span>
<span id="cb32-328"><a href="#cb32-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-329"><a href="#cb32-329" aria-hidden="true" tabindex="-1"></a><span class="fu">## Proporções populacional e amostral {#sec-popamostra}</span></span>
<span id="cb32-330"><a href="#cb32-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-331"><a href="#cb32-331" aria-hidden="true" tabindex="-1"></a>O conceito de proporção é o mesmo que o conceito de frequência relativa e o conceito de probabilidade de sucesso em um experimento binomial, discutidos anteriormente, na distribuição binomial.</span>
<span id="cb32-332"><a href="#cb32-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-333"><a href="#cb32-333" aria-hidden="true" tabindex="-1"></a>A frequência relativa de uma categoria ou classe dá a proporção da amostra ou população que pertence a essa categoria ou classe. Da mesma forma, a probabilidade de sucesso em um experimento binomial representa a proporção da amostra ou população que possui uma determinada característica.</span>
<span id="cb32-334"><a href="#cb32-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-335"><a href="#cb32-335" aria-hidden="true" tabindex="-1"></a>A proporção populacional, representada por *p*, é obtida considerando a razão entre o número de elementos em uma população com uma característica específica e o número total de elementos na população. A proporção amostral, denotada por $\hat{p}$ (pronuncia-se p-chapéu), fornece uma proporção semelhante para uma amostra.</span>
<span id="cb32-336"><a href="#cb32-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-337"><a href="#cb32-337" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-338"><a href="#cb32-338" aria-hidden="true" tabindex="-1"></a>p = \frac{X}{N} \quad e \quad \hat{p}= \frac{x}{n}</span>
<span id="cb32-339"><a href="#cb32-339" aria-hidden="true" tabindex="-1"></a>$$ onde,</span>
<span id="cb32-340"><a href="#cb32-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-341"><a href="#cb32-341" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*N* $\to$ número total de elementos em uma população</span>
<span id="cb32-342"><a href="#cb32-342" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*n* $\to$ número total de elementos em uma amostra</span>
<span id="cb32-343"><a href="#cb32-343" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*X* $\to$ número de elementos na população que possui determinada característica</span>
<span id="cb32-344"><a href="#cb32-344" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>*x* $\to$ número de elementos na amostra que possui determinada característica</span>
<span id="cb32-345"><a href="#cb32-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-346"><a href="#cb32-346" aria-hidden="true" tabindex="-1"></a>Como no caso da média, a diferença entre a proporção amostral e a proporção populacional correspondente, determina o *erro amostral*, assumindo que a amostra é aleatória e nenhum erro não amostral foi cometido. Ou seja,</span>
<span id="cb32-347"><a href="#cb32-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-348"><a href="#cb32-348" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-349"><a href="#cb32-349" aria-hidden="true" tabindex="-1"></a>erro \quad amostral = \hat{p} - p</span>
<span id="cb32-350"><a href="#cb32-350" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-351"><a href="#cb32-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-352"><a href="#cb32-352" aria-hidden="true" tabindex="-1"></a>A **distribuição amostral de uma proporção** é a distribuição das proporções de todas as amostras possíveis de tamanho *n* retiradas de uma população.</span>
<span id="cb32-353"><a href="#cb32-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-354"><a href="#cb32-354" aria-hidden="true" tabindex="-1"></a>De acordo com o Teorema Central do Limite, para amostras suficientemente grandes, a distribuição de $\hat{p}$ se aproxima de uma distribuição normal, mesmo que os dados originais sejam binomiais (sucesso/fracasso), desde que: $np \geq 5$ e $n(1 - p) \geq 5$.</span>
<span id="cb32-355"><a href="#cb32-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-356"><a href="#cb32-356" aria-hidden="true" tabindex="-1"></a>Assim,</span>
<span id="cb32-357"><a href="#cb32-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-358"><a href="#cb32-358" aria-hidden="true" tabindex="-1"></a>$$E(\hat{p})=\mu_\hat{p}$$</span>
<span id="cb32-359"><a href="#cb32-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-360"><a href="#cb32-360" aria-hidden="true" tabindex="-1"></a>$$Var(\hat{p})=\sigma^2_\hat{p}=\frac{\hat{p}(1-\hat{p})}{n}$$ Logo,</span>
<span id="cb32-361"><a href="#cb32-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-362"><a href="#cb32-362" aria-hidden="true" tabindex="-1"></a>$$E(\hat{p})=\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$$</span>
<span id="cb32-363"><a href="#cb32-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-364"><a href="#cb32-364" aria-hidden="true" tabindex="-1"></a>Dessa forma, a distribuição amostral de $\hat{p}$ será:</span>
<span id="cb32-365"><a href="#cb32-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-366"><a href="#cb32-366" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-367"><a href="#cb32-367" aria-hidden="true" tabindex="-1"></a>\hat{p} \sim N(\hat{p}, \frac{\hat{p}(1-\hat{p})}{n})</span>
<span id="cb32-368"><a href="#cb32-368" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-369"><a href="#cb32-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-370"><a href="#cb32-370" aria-hidden="true" tabindex="-1"></a>Quando não conhecemos a proporção populacional *p*, pode-se usar $\hat{p}$ como estimativa dessa proporção, desde que as condições acima sejam satisfeitas.</span>
<span id="cb32-371"><a href="#cb32-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-372"><a href="#cb32-372" aria-hidden="true" tabindex="-1"></a>Dessa forma, pode-se calcular probabilidades aproximadas por uma distribuição normal com média $μ = n \times p$ e $σ = \sqrt{(n×p(1-p))}$ (veja também @sec-mudpbinom).</span>
<span id="cb32-373"><a href="#cb32-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-374"><a href="#cb32-374" aria-hidden="true" tabindex="-1"></a>Considerando a "população", usada neste capítulo, o conjunto de dados <span class="in">`dadosMater.xlsx`</span>, será verificado a proporção de mulheres fumantes. Inicialmente, a variável <span class="in">`fumo`</span>, que está como variável numérica, será transformada em fator:</span>
<span id="cb32-375"><a href="#cb32-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-378"><a href="#cb32-378" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-379"><a href="#cb32-379" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-380"><a href="#cb32-380" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(fumo) <span class="sc">%&gt;%</span> </span>
<span id="cb32-381"><a href="#cb32-381" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fumo =</span> <span class="fu">factor</span>(fumo, </span>
<span id="cb32-382"><a href="#cb32-382" aria-hidden="true" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb32-383"><a href="#cb32-383" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Fumante"</span>, <span class="st">"Não fumante"</span>)))</span>
<span id="cb32-384"><a href="#cb32-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-385"><a href="#cb32-385" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-386"><a href="#cb32-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-387"><a href="#cb32-387" aria-hidden="true" tabindex="-1"></a>A proporção de fumantes, frequência relativa (*fr*) é:</span>
<span id="cb32-388"><a href="#cb32-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-391"><a href="#cb32-391" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-392"><a href="#cb32-392" aria-hidden="true" tabindex="-1"></a>fumo <span class="ot">&lt;-</span> <span class="fu">with</span>(dados, <span class="fu">table</span>(fumo))</span>
<span id="cb32-393"><a href="#cb32-393" aria-hidden="true" tabindex="-1"></a>fr.fumo <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(fumo)</span>
<span id="cb32-394"><a href="#cb32-394" aria-hidden="true" tabindex="-1"></a>fr.fumo</span>
<span id="cb32-395"><a href="#cb32-395" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-396"><a href="#cb32-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-397"><a href="#cb32-397" aria-hidden="true" tabindex="-1"></a>A saída retorna que a proporção de fumantes entre as mulheres desse arquivo é <span class="in">`r round(fr.fumo[1], 2)`</span>. Esta será considerada a proporção *p* da ‘população’. Agora, imagine que esse resultado fosse desconhecido. Então, para saber a qual a proporção de fumantes dessa ‘população’, seria necessário extrair uma amostra adequada. Foi selecionada uma amostra de n = 100 da ‘população’ alvo:</span>
<span id="cb32-398"><a href="#cb32-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-401"><a href="#cb32-401" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-402"><a href="#cb32-402" aria-hidden="true" tabindex="-1"></a> <span class="fu">set.seed</span>(<span class="dv">134</span>)</span>
<span id="cb32-403"><a href="#cb32-403" aria-hidden="true" tabindex="-1"></a> amostra.fumo <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">100</span>)</span>
<span id="cb32-404"><a href="#cb32-404" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-405"><a href="#cb32-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-406"><a href="#cb32-406" aria-hidden="true" tabindex="-1"></a>Usando a <span class="in">`amostra.fumo`</span>, calcula-se a proporção de fumantes:</span>
<span id="cb32-407"><a href="#cb32-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-410"><a href="#cb32-410" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-411"><a href="#cb32-411" aria-hidden="true" tabindex="-1"></a> tabagismo <span class="ot">&lt;-</span> <span class="fu">with</span>(amostra.fumo, <span class="fu">table</span>(fumo))</span>
<span id="cb32-412"><a href="#cb32-412" aria-hidden="true" tabindex="-1"></a> fr <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(tabagismo)</span>
<span id="cb32-413"><a href="#cb32-413" aria-hidden="true" tabindex="-1"></a> fp <span class="ot">&lt;-</span> fr<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb32-414"><a href="#cb32-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-415"><a href="#cb32-415" aria-hidden="true" tabindex="-1"></a> tab.fumo <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">n =</span> tabagismo,</span>
<span id="cb32-416"><a href="#cb32-416" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fr =</span> <span class="fu">round</span>(fr, <span class="dv">2</span>),</span>
<span id="cb32-417"><a href="#cb32-417" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fp =</span> <span class="fu">round</span>(fp, <span class="dv">2</span>))</span>
<span id="cb32-418"><a href="#cb32-418" aria-hidden="true" tabindex="-1"></a> tab.fumo</span>
<span id="cb32-419"><a href="#cb32-419" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-420"><a href="#cb32-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-421"><a href="#cb32-421" aria-hidden="true" tabindex="-1"></a>A proporção de uma amostra é uma variável aleatória: varia de amostra para amostra de uma forma que não pode ser prevista com certeza. O Teorema Central do Limite se aplica em proporções. À medida que novas amostras forem extraídas, o valor da proporção amostral $\hat{p}$ se aproxima da proporção populacional *p*. Na "população" *p* = 0,22; na amostra de n = 100, $\hat{p}$ = <span class="in">`r tab.fumo[1,2]`</span>. Para amostras grandes, a proporção amostral tem distribuição aproximadamente normal com as seguinte características mencionadas acima em relação a $\mu_\hat{p}$ e $\sigma_\hat{p}$.\</span>
<span id="cb32-422"><a href="#cb32-422" aria-hidden="true" tabindex="-1"></a>Como verificar se uma amostra é grande?</span>
<span id="cb32-423"><a href="#cb32-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-424"><a href="#cb32-424" aria-hidden="true" tabindex="-1"></a>Uma amostra é grande se o intervalo</span>
<span id="cb32-425"><a href="#cb32-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-426"><a href="#cb32-426" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-427"><a href="#cb32-427" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">\hat{p}-3 \times \sigma_\hat{p} , \quad \hat{p}-3 \times \sigma_\hat{p}</span><span class="co">]</span></span>
<span id="cb32-428"><a href="#cb32-428" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-429"><a href="#cb32-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-430"><a href="#cb32-430" aria-hidden="true" tabindex="-1"></a>estiver totalmente dentro do intervalo <span class="sc">\[</span>0,1<span class="sc">\]</span>.</span>
<span id="cb32-431"><a href="#cb32-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-432"><a href="#cb32-432" aria-hidden="true" tabindex="-1"></a>Na prática, *p* não é conhecido, portanto, $\sigma_\hat{p}$ também não é. Nesse caso, para verificar se a amostra é suficientemente grande, substitui-se o valor de *p* pelo valor conhecido de $\hat{p}$. Isso significa verificar se o intervalo</span>
<span id="cb32-433"><a href="#cb32-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-434"><a href="#cb32-434" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-435"><a href="#cb32-435" aria-hidden="true" tabindex="-1"></a>\hat{p}-3\times\sqrt{\frac{\hat{p}(1-\hat{p})}{n}},\quad \hat{p}+3\times\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}</span>
<span id="cb32-436"><a href="#cb32-436" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-437"><a href="#cb32-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-438"><a href="#cb32-438" aria-hidden="true" tabindex="-1"></a>encontra-se totalmente dentro do intervalo <span class="sc">\[</span>0,1<span class="sc">\]</span>.</span>
<span id="cb32-439"><a href="#cb32-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-440"><a href="#cb32-440" aria-hidden="true" tabindex="-1"></a>Transportando os dados da amostra de gestantes, para a fórmula e usando o *R* para o cálculo, tem-se:</span>
<span id="cb32-441"><a href="#cb32-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-444"><a href="#cb32-444" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-445"><a href="#cb32-445" aria-hidden="true" tabindex="-1"></a>p.chapeu <span class="ot">&lt;-</span> tab.fumo[<span class="dv">1</span>,<span class="dv">2</span>]</span>
<span id="cb32-446"><a href="#cb32-446" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> tab.fumo[<span class="dv">1</span>,<span class="dv">1</span>] <span class="sc">+</span> tab.fumo[<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb32-447"><a href="#cb32-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-448"><a href="#cb32-448" aria-hidden="true" tabindex="-1"></a>li <span class="ot">&lt;-</span> p.chapeu <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n)</span>
<span id="cb32-449"><a href="#cb32-449" aria-hidden="true" tabindex="-1"></a>ls <span class="ot">&lt;-</span> p.chapeu <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n)</span>
<span id="cb32-450"><a href="#cb32-450" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(li, ls), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb32-451"><a href="#cb32-451" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-452"><a href="#cb32-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-453"><a href="#cb32-453" aria-hidden="true" tabindex="-1"></a>Como os limites ficam no intervalo <span class="sc">\[</span>0, 1<span class="sc">\]</span>, chega-se à conclusão de que a amostra de *n* = 100 é aceitável para estimar a proporção populacional.</span>
<span id="cb32-454"><a href="#cb32-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-455"><a href="#cb32-455" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb32-456"><a href="#cb32-456" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercício</span></span>
<span id="cb32-457"><a href="#cb32-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-458"><a href="#cb32-458" aria-hidden="true" tabindex="-1"></a>Uma amostra com tamanho n = 40 é suficiente?</span>
<span id="cb32-459"><a href="#cb32-459" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb32-460"><a href="#cb32-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-461"><a href="#cb32-461" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Resposta</span><span class="co">]</span>{.underline}:</span>
<span id="cb32-462"><a href="#cb32-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-465"><a href="#cb32-465" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-466"><a href="#cb32-466" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">40</span></span>
<span id="cb32-467"><a href="#cb32-467" aria-hidden="true" tabindex="-1"></a>li <span class="ot">&lt;-</span> p.chapeu <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n) </span>
<span id="cb32-468"><a href="#cb32-468" aria-hidden="true" tabindex="-1"></a>ls <span class="ot">&lt;-</span> p.chapeu <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sqrt</span>((p.chapeu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p.chapeu))<span class="sc">/</span>n)</span>
<span id="cb32-469"><a href="#cb32-469" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(li, ls), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb32-470"><a href="#cb32-470" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-471"><a href="#cb32-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-472"><a href="#cb32-472" aria-hidden="true" tabindex="-1"></a>Sim, é aceitável uma amostra de n = 40.</span>
</code><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>